### ISSUE TITLE
Add padlock icon to private data sets

### ISSUE THREAD

**Issue by sara-koordinates** [koordinates/koordinates-qgis-plugin#144]
Some data sets are not publicly available. 

- Data card: please add a padlock icon to the left of the Starred icon
- Data sheet:  please add a padlock icon next to the title of the dataset

From Hamish:
Every dataset will have a `public_access` attribute - if it's `null` then the data is private

Icon:
![padlock](https://user-images.githubusercontent.com/110858727/198926386-de77ff44-f739-4868-9f03-23ced9f7110c.svg)

![image](https://user-images.githubusercontent.com/110858727/198926248-6eb6dc7a-4980-433a-98f8-7a6b6c530cbf.png)

![image](https://user-images.githubusercontent.com/110858727/198926220-561358ba-2380-4ccd-882c-32ea93c56f96.png)

**Comment by BallJonathan** [comment]
If we can fit this one in, that would be great.
