### ISSUE TITLE
Large repository cloning appears to stall, then begins

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#159]
**Describe the bug**
More a poor experince than a bug, when cloning a large dataset, QGIS commences cloning, but the progress bar stays on 0%, with the mouse spinning. At this time QGIS is unsuasble. After 30 seconds to 1 min, the progress bar becomes active, and the mouse stops spinning. Through out the cloning process the QGIS is largely unusable.

**Comment by nyalldawson** [comment]
This one is actually coming from the kart plugin. I suggest we move the clone progress to a background thread (a qgis "task") so that users aren't blocked while it executes.

**Comment by nyalldawson** [comment]
This is fixed with the move to background tasks
