### ISSUE TITLE
WARNING Authorization failed

### ISSUE THREAD

**Issue by JorisFransman** [koordinates/koordinates-qgis-plugin#163]
**Describe the bug**

**To Reproduce**
Installed the Koordinates plugin via plugin manager.
Installed Kart via 
Open Koordinates via plugins>Koordinates>"Show data browser"
Click "Login with your Koordinates ID" button in data browser.
In a Firefox browser that opens fill in Koordinates credentials
Authorize Koordinates the it will show his message:

```
QGIS Koordinates Plugin authorized

You can close this window and return to QGIS to start browsing and adding data

```
In QGIS open log messages via View>Panels>Log Messages to find this log message:

`WARNING Authorization failed: {"errors":{"detail":"Invalid user"},"status_code":403}
`

**Expected behavior**

Login button disappearing and  data to be browsed visible.

**Screenshots**
N/A

**Version info (this is important!):**

QGIS 3.22.4-Białowieża
Koordinates 1.0.2
Kart Installed version | 1.0.4
OS Ubuntu 22.04.1 LTS
Browser Firefox 108.0b3 (64-bit)

```
Kart Plugin version
1.0.4
QGIS version
3.22.4-Białowieża
Operating system
Linux 5.15.0 53 generic x86_64 with glibc2.35
Kart version
Kart v0.11.5, Copyright (c) Kart Contributors
» GDAL v3.4.0; PROJ v6.3.0
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.33.GIT
» SQLAlchemy v1.4.40; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.1; Libpq v10.0.12
» SpatialIndex v1.9.3
```

**Additional context**
NSTR

**Comment by BallJonathan** [comment]
Thanks Joris. We will look into this.
Jonathan Ball
koordinates.com / @koordinates <http://twitter.com/koordinates>

**Comment by BallJonathan** [comment]
Another user is having the same issue. Logs in, authorises, returns to QGIS and receives the following message. >3.22 Windows
![image](https://user-images.githubusercontent.com/113562913/203858030-73dfef39-f843-4e33-b27d-09c160ae4820.png)

**Comment by nyalldawson** [comment]
@BallJonathan to clarify: is this a backend issue?

**Comment by pfw** [comment]
@nyalldawson It's safe to assume that at the moment until we get to the bottom of it.

**Comment by pfw** [comment]
@JorisFransman Could you please try with this test version? You will need to 'install from zip' in the plugin manager.

[koordinates.zip](https://github.com/koordinates/koordinates-qgis-plugin/files/10100877/koordinates.zip)

**Comment by BallJonathan** [comment]
Short-term solution:
- Visit https://koordinates.com/explore/
- Log in using your existing account information
- Return to QGIS and try logging in again

**Comment by hamishcampbell** [comment]
@nyalldawson the backend issue should now be fixed, but it would be ideal if the message was improved in QGIS for future cases where the user might not have permissions for whatever reason.
