### ISSUE TITLE
Pressing cancel during auth process appears to succeed

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/koordinates-qgis-plugin#164]
**Describe the bug**

During the login process, the Koordinates site gives you the option to Authorize access to your account or to "cancel" the process. Cancelling the process correctly rejects the login however the user is presented with the success screen.

**To Reproduce**

While logged in to Koordinates.com already (but logged out of the QGIS plugin):

1. From the QGIS plugin press "Login"
2. The authorize screen is opened in browser. Press "Cancel"
3. See the final screen.

**Expected behavior**

The page presented to the user should indicate that the app was *not* authorized to access the account.

**Screenshots**

Cancelling auth:

<img width="688" alt="Screenshot 2022-11-23 at 8 46 10 AM" src="https://user-images.githubusercontent.com/295074/203407906-cca6422c-5de3-4fc7-9513-e0ce6ce71cb3.png">

Resulting message:

<img width="665" alt="Screenshot 2022-11-23 at 8 46 55 AM" src="https://user-images.githubusercontent.com/295074/203407928-c7bcb9d1-1968-4c5c-aa32-918aae867925.png">

Noting the correct response in QGIS:

<img width="585" alt="Screenshot 2022-11-23 at 8 47 07 AM" src="https://user-images.githubusercontent.com/295074/203407951-b4d5d040-cefc-4bc8-8f90-e1cd34c3b0f7.png">

**Version info (this is important!):**

```
QGIS version: 27.0-Master
QGIS code revision: 2e622be6f9

Koordinates Plugin: 1.0.2
````

**Comment by rcoup** [comment]
URLs I see in Chrome:

1. `GET https://id.koordinates.com/o/authorize/?scope=read&response_type=code&response_mode=query&client_id=DDDD&code_challenge=AAAA&state=BBBB&code_challenge_method=S256&redirect_uri=http://127.0.0.1:8989/&code_challenge=CCCC&code_challenge_method=S256`
→ 200; Authorise screen.

2. Click Cancel: `POST https://id.koordinates.com/o/authorize/?scope=read&response_type=code&response_mode=query&client_id=DDDD&code_challenge=AAAA&state=BBBB&code_challenge_method=S256&redirect_uri=http://127.0.0.1:8989/&code_challenge=CCCC&code_challenge_method=S256`
 → 302 → `http://127.0.0.1:8989/?error=access_denied&state=BBBB`

3. `GET http://127.0.0.1:8989/?error=access_denied&state=BBBB`
 → 302 → `https://<internal-host>/o/authorize/qgis/`

4. `GET https://<internal-host>/o/authorize/qgis/`
 → 400; "Success screen"

* the host the QGIS plugin is redirecting to in (3) needs to be `id.koordinates.com` as well.
* adding `?error=access_denied` to `/o/authorize/qgis/` in (3) will mean in (4) we can display different template text. I will organise that.

**Comment by nyalldawson** [comment]
Thanks @rcoup -- I've got a fix all rest for this, I just need the new "cancelled" page url 👍

**Comment by hamishcampbell** [comment]
@nyalldawson the cancellation page URL will be `https://id.koordinates.com/o/authorize/qgis/cancelled/` - that will be live shortly.
