### ISSUE TITLE
Grid (DEM/DSM) layers are listed but can’t be added to QGIS map

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#165]
**Describe the bug**
Grid (DEM/DSM) layers are listed but can’t be added to QGIS map

**To Reproduce**
Steps to reproduce the behaviour:
1. Find Grid in the browser.
2. No "Add+" button is available.

**Expected behaviour**
Grid layers should have an add button which allows you to add grids to the map via WMTS

**Screenshots**
<img width="509" alt="image" src="https://user-images.githubusercontent.com/113562913/203428826-96962681-9354-4487-9aaf-2206bf7c145d.png">

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): All
 - QGIS, Kart & Plugin details: 1.0.2

**Comment by nyalldawson** [comment]
@pfw this was fixed by https://github.com/koordinates/koordinates-qgis-plugin/pull/162 wasn't it?

**Comment by pfw** [comment]
Correct.
