### ISSUE TITLE
Change "Clone V" button to "Get V"

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#170]
**Feature? Please describe.**
Update the "Clone" Button to "Get V" button. 
E.g 
From this:
<img width="191" alt="Screen Shot 2022-12-05 at 3 31 55 PM" src="https://user-images.githubusercontent.com/113562913/205536630-21588d9f-6943-4c2a-a098-f8a1862fe16e.png">

To this:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/113562913/205536489-4ee9ff1d-f094-40cf-99f8-db6a7d9fdb05.png">
Note: Leave "Map +" as is.

And replace the word "Clone" with "Get data repository" in the clone window header 
![image](https://user-images.githubusercontent.com/113562913/205537153-2de0d1b6-98cf-49cb-bfdb-530ce4d505ef.png)

**Comment by nyalldawson** [comment]
Does this extend everywhere?

Specifically:

- When a user doesn't have clone capabilities, we show a message: " To clone cloud-hosted data to your local drive, please request access."
- When clone is successful the message: "Repository correctly cloned"
- Message "Kart plugin must be installed to clone repositories"
- Label: "Select Directory to Clone To"

**Comment by BallJonathan** [comment]
Good spotting. I think those are all alright for now.

   - When a user doesn't have clone capabilities, we show a message: " To
   clone cloud-hosted data to your local drive, please request access."
   - When clone is successful the message: "Repository correctly cloned"
   - Message "Kart plugin must be installed to clone repositories"
   - Label: "Select Directory to Clone To"
