### ISSUE TITLE
Add spatial query support (V2.0.0)

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#178]
**Is your feature request related to a problem? Please describe.**

At present "Add +" adds a XYZ tile layer to the QGIS map. We want users to be able to complete 1 click spatial queries as they do in the web portal. 

Here is a video of the feature on the web portal:
 
https://user-images.githubusercontent.com/113562913/207744129-14f58d1a-6879-48e6-a37c-9e9524d0fcf6.mov

**Describe the solution you'd like**
-Switch 'Add+' to use the WMTS tiles
-Add WMTS 'getfeatureinfo' support, so when a user clicks on the map with the 'Identify Features' tool, relevant results appear in the 'identify result' panel

Here are some specs on ['getfeatureinfo' ](https://portal.ogc.org/files/?artifact_id=35326)

**Comment by nyalldawson** [comment]
@BallJonathan how do I get the wmts url for a dataset?

**Comment by hamishcampbell** [comment]
```
https://koordinates.com/services;key={api-key}/wmts/1.0.0/layer/{id}/WMTSCapabilities.xml
```

**Comment by nyalldawson** [comment]
Thanks @hamishcampbell ! Down with the dreaded 🤧 today, but I'll see if I can squeeze this one in...

**Comment by BallJonathan** [comment]
This should be unblocked now.
