### ISSUE TITLE
Add Point Cloud Support (V2.0.0)

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#182]
Add point [cloud support as per designs](https://www.figma.com/proto/Qr3WsvWKwIWtIpZBfyI6Gj/QGIS-plugin-design-v2a?page-id=1624%3A56395&node-id=1624-61050&viewport=1791%2C1641%2C0.16&scaling=min-zoom&starting-point-node-id=1624%3A61874).

- Adds PC data cards with new icon. No Thumbnail at present
- Adds PC Datasheets
- Adds PC filter options
- "Add+" delivers a bounding box to map the project (WMTS)
- "Get V" starts clone process

**Comment by nyalldawson** [comment]
Closed by #196 (and others)
