### ISSUE TITLE
 Improved clone status bar messages (V2.0.0)

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#184]
Once cloning becomes a background process, we need to improve the status bar messages we provide to users. 

Please follow [these designs](https://www.figma.com/file/MraaBPZS2lIn2329VW0pBA/QGIS-plugin---Clone-process-v2?node-id=31%3A13625&t=66ICmfMNQvGTzNHp-1) for various situations a user might encounter while cloning, or multi cloning.

**Comment by nyalldawson** [comment]
Fixed by https://github.com/koordinates/koordinates-qgis-plugin/pull/190
