### ISSUE TITLE
Starred filter drop downs get stuck in tab switch

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#211]
If you have a start filter drop-down open, and switch tabs, the drop-down gets stuck over the top of the new tab. 

https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/d9ad2282-8859-4ec6-a672-898acaad1d1f

**Comment by nyalldawson** [comment]
Fixed by https://github.com/koordinates/koordinates-qgis-plugin/pull/253
