### ISSUE TITLE
Close filter drop-down on click anywhere. Not just the minimise button. 

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#212]
General UI issue:

I think we have discussed this in the past. You can only close/minimise a drop-down by clicking the small triangle button. Ideally clicking anywhere outside of the drop-down box would minimise the drop-down. Is this possible? If so it would be good to implement on all plug-in drop downs.

**Comment by nyalldawson** [comment]
Also publisher drop down should immediately collapse after a choice is made
