### ISSUE TITLE
Thumbnails disappear at some plugin widths

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#217]
We would like the datacard thumbnails to be present at all plug-in widths, expect the smallest. At present the thumbnails disappear briefly as the pop/Browse/pub/recent tabs move the the left. 

https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/8fd47a57-d2c6-4947-978c-a761326518f3

**Comment by nyalldawson** [comment]
Bump out wide panel mode threshold to be large enough to handle this
