### ISSUE TITLE
Popular panel does not match design

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#218]
**Describe the bug**
Popular panel does not match design

**To Reproduce**
1. Open the Koordinates plugin and select the Browse tab
2. Browse tab looks different from proposed design:
- Reduce padding above and below title
- Add ‘View all’ button
- Thumbnails on cards
- Add stroke to panel
- Remove stroke from cards

**Expected behavior**
Popular panel layout matches design

**Screenshots**

Proposed design:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/6649e1e9-cca5-4d50-920d-d226eda96537)
 
Implementation:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/6b711591-2737-4d11-812b-417778ff4ea2)

**Version info (this is important!):**
Kart Plugin version
1.0.11

QGIS version
3.30.0-'s-Hertogenbosch

Operating system
macOS 13.3.1 x86_64 i386 64bit

Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

**Comment by nyalldawson** [comment]
Ignore: Add ‘View all’ button-- that's deferred
