### ISSUE TITLE
Context switcher presentation

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#219]
**Describe the bug**
Visual issues with context switcher menu.

**To Reproduce**
1. Open context switcher
2. Menu looks like this:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/b6f4e41b-a4c4-4a80-989e-314c95c12e44)

**Expected behavior**
- User avatar is included
- Data service logo aspect ratio is preserved

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS):
 Mac OS

 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

```

**Comment by BallJonathan** [comment]
@brentneave can you invite nyall@north-road.com to be a paid seat at relaxing ducks incorperated?
