### ISSUE TITLE
Show total counts in publisher tab bar

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#222]
**Describe the bug**
Publisher type filter tabs do not match proposed design.

**To Reproduce**
1. Open Browse tab and open the publishers filter, or visit the Publishers tab.
2. Publisher type filters do not match the proposed design.

**Expected behavior**
- Tab labels should be left aligned 
- Tabs should contract to fit labels rather than expand to occupy available space
- Labels are missing item counts

**Screenshots**
Proposed design:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/3d2f7cba-7780-4344-a42d-008eaff0ca23)

Implementation:
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/69de364f-e12d-4e46-a4c8-aa4d458b704e)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS
 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

```

**Comment by nyalldawson** [comment]
Will follow up on slack to find out api for total counts
