### ISSUE TITLE
Python error when switching to My Data tab

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#223]
**Describe the bug**

**To Reproduce**
1. Click on My Data.
2. Tab contents do not update to show My Data.
3. Python error message displays in QGIS.

**Expected behavior**
My Data tab is displayed without an error.

**Screenshots**
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/68e5f7d7-0836-4f11-aa25-81a781b74e8f)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS

 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

```

**Comment by BallJonathan** [comment]
@nyalldawson This is a issue specific to "pro" accounts. Are you able to signup using a credit card and we will reimburse you?
