### ISSUE TITLE
Error when cloning 

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#224]
**Describe the bug**
Error when cloning after hitting clone and setting path to ~/Kart

**To Reproduce**
1. Click “Clone” on NZ Property titles.
2. In the clone dialog, select a folder in your user home folder (`~` on MacOS) named Kart (not sure if specific folders path is necessary to reproduce error), and other options as per the screenshot below.
3. An error occurs and the dataset cannot be cloned.

**Expected behavior**
The dataset should clone as expected, or if it is too big to clone, offer a way for the user to recover by not cloning the dataset or applying a spatial filter.

**Screenshots**
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/c4fe4d31-347d-4224-b8f4-0c02e39e7eec)
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/4f1db1f6-a0e8-479a-9948-2faa34e6b596)
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/8672bdd2-ea98-4fa7-8c30-887391610535)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS
 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4
```

**Comment by BallJonathan** [comment]
@nyalldawson This seems to be solved now!
