### ISSUE TITLE
Should typing a site name show matches in the publisher filter?

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#225]
**Is your feature request related to a problem? Please describe.**
To discuss. Should typing a site name show matches in the publisher filter?
- Typing the name of a publisher displays matches as it should.
- Typing the name of a site does not show any matches, but it may not be unreasonable to type in “LRIS” for instance and expect results.
- Interested in others’ thoughts on this, it makes sense to me but others might not expect it to work this way?
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/fbfa910d-0815-44c8-8934-5dea3a47633d)

**Describe the solution you'd like**
When filtering publishers, display matches on the portal name as well as the publisher name.

**Describe alternatives you've considered**
We could include a site filter somewhere, but that requires a bit more consideration first.

**Comment by nyalldawson** [comment]
Fixed in latest version
