### ISSUE TITLE
Clicking Pro user in publishers tab gives incorrect results. 

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#226]
When clicking on a pro user within the publishes tab, we should be showing only layers published by that pro user. At present it is showing us all layers published on the platform.

https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/d627102a-4a0a-47e3-8640-5e8b62788fdf

**Comment by nyalldawson** [comment]
Can't reproduce right now

**Comment by nyalldawson** [comment]
No longer reproducible
