### ISSUE TITLE
Pro User and Mirrored Publisher Headers incorrect. 

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#227]
Pro user and mirrored publisher headers are displaying incorrectly.  At present they are white text on a light grey background, making them almost unreadable.

<img width="557" alt="image" src="https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/508ca11c-f0ab-41df-9c0b-b9b84acb54d8">

<img width="573" alt="image" src="https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/5750b71f-dc0b-4534-aceb-c9e5af86e249">

**Comment by nyalldawson** [comment]
Need to use a different text color for these -- publishers will always have light text, users need dark

**Comment by nyalldawson** [comment]
![c7298081-c2db-4cf1-9a8b-687f9c34782a](https://github.com/koordinates/koordinates-qgis-plugin/assets/1829991/096edb50-1db4-4ef3-b13e-b16caf2f870b)
