### ISSUE TITLE
Publisher filter and tab behaviour is incorrect

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#229]
**Describe the bug**
Publisher filter and tab behaviour is incorrect

**To Reproduce**
- Type “Blair” into the publisher filter
- Blair Rogers will show up at the top of the “All” tab
- Try and narrow your results down to users only by clicking the “Users” tab
- A first click of the “Users” tab resets the filter keyword but does not select the “Users” tab
- A second click of the “Users” tab selects the tab, displays all users instead of the results of the filter, since the filter keyword has been reset

**Expected behavior**
- The user tab is selected after a single click 
- The keyword filter is not reset when changing tabs
- The filter is preserved and only “Blair Rogers” (and any other matches) are visible under the “Users” tab

**Screenshots**
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/865555ee-d583-4a9d-a9f9-6325209b7126)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS
 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

```

**Comment by nyalldawson** [comment]
Don't clear filter on changing tabs
Don't automatically change tabs when entering filter
