### ISSUE TITLE
“Load more…” button appears over the top of search results in data browser

### ISSUE THREAD

**Issue by brentneave** [koordinates/koordinates-qgis-plugin#233]
**Describe the bug**
“Load more…” button appears over the top of search results in data browser

**To Reproduce**
1. Scroll the data browser up and down a bit
2. A “Load more” button will sometimes appear over the top of results

**Expected behavior**
Load more button doesn’t appear over results

**Screenshots**
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/11057040/08cbd32f-a476-4b0e-b6c1-bdde9db1552a)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): MacOS
 - QGIS, Kart & Plugin details:
  ```
Kart Plugin version
1.0.11
QGIS version
3.30.0-'s-Hertogenbosch
Operating system
macOS 13.3.1 x86_64 i386 64bit
Kart version
Kart v0.12.2, Copyright (c) Kart Contributors
» GDAL v3.6.2; PROJ v9.1.1; PDAL v2.4.3
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.38.1; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.0; SpatiaLite v5.0.1; Libpq v14.0.4

```

**Comment by nyalldawson** [comment]
Note: only showing when panel is small enough that thumbnails are hidden
