### ISSUE TITLE
Selecting Pro user in Publishers filter shows incorrect results. 

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#271]
Selecting a pro user in the publishes filter shows all platform data sets. 

https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/3a108a0c-6da8-4e2c-a08b-73aff45fa2dd

**Comment by nyalldawson** [comment]
I can't reproduce this one:

Any clues what else I need to do to replicate?

https://github.com/koordinates/koordinates-qgis-plugin/assets/1829991/acb56949-5914-4d2e-afe0-1ff0e681e9f1

**Comment by nyalldawson** [comment]
No longer reproducible
