### ISSUE TITLE
Publisher counts not showing

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#272]
Publisher counts are not displaying correctly in the publisher filter tab. They seem to be fine in the drop down menu
<img width="735" alt="Screenshot 2023-06-14 at 11 24 14 AM" src="https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/2b15e24f-aa00-49bd-af0c-c5c097f0f956">
<img width="325" alt="Screenshot 2023-06-14 at 11 25 30 AM" src="https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/513d9a31-e86f-47f9-a5be-82f94a406ae3">

**Comment by nyalldawson** [comment]
@BallJonathan we'll need to do some live remote debugging on this one -- they are working correctly for me so I need to see what requests are being sent on your system:

![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/1829991/4a85408f-34e0-4fcc-82ef-21f5b83b9a49)

**Comment by nyalldawson** [comment]
No longer reproducible
