### ISSUE TITLE
Add new cloning rule

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#274]
As cloning in in Beta phase, we are fine tuning permissions around who can clone what data.

In the API `repository` objects now have a `user_capabilities` attribute. This is a list of stuff. If the list contains `can-clone` - the user can clone it now. If it has `can-request-clone` then the user will be able to clone after requesting access from us. If neither flag is there, the repository is not cloneable by the user.

Previous/Current  behaviour:
- Only users with karthub flag are able to clone data.
- Users without the flag, receive a popup modal when they click "get", asking them to request accessing to cloning features. Once approved, they can clone anything they have access to. 

New Behaviour:
- All users can clone some data (mirrored data)
- Paid seats and pro users can clone their own/orgs data
- All other users can request access to clone any publicly accessible data. When they click 'get' they get the same popup modal. Once approved, they can clone anything they have access to.

**Comment by BallJonathan** [comment]
@skim618 Does that all sound correct to you? I expect Nyall will have some questions related to this task, so please watch out

**Comment by skim618** [comment]
> New Behaviour:
> 
> All users can clone some data (mirrored data)
> Paid seats and pro users can clone their own/orgs data
> All other users can request access to clone any publicly accessible data. When they click 'get' they get the same popup modal. Once approved, they can clone anything they have access to.

Above sounds correct. Like Hamish has said, 

> In the API repository objects now have a `user_capabilities` attribute. This is a list of stuff. If the list contains `can-clone` the user can clone it now. If it has `can-request-clone` then the user will be able to clone after requesting access from us. If neither flag is there, the repository is not cloneable by the user. 

If I was to summarise the currently implemented logic in more detail it would be.
The user `can-clone` if any of the following are true:
- If the mapstream of the data is scraped, 
- If the user has `enable_kart_clone` enabled **and** the data is public
- The user is a superuser
- The user is logged in **and** The mapstream that owns the data is their user mapstream (this covers the pro-user case)
- The user is logged in **and** They're a paid seat for the org that owns the mapstream that owns the data (the org paid seat case)

`can-request-clone` is granted for users means that can't currently clone the data, but could if the "enable_kart_clone" flag was enabled.

**Comment by BallJonathan** [comment]
@nyalldawson 

Ok, so I have a better understanding of this issue now. The cloning policy is working as it should currently, but it was envisaged that we would implement it differently and have elements of the UI (the 'Get' button) respond to certain settings. 

Currently, all Datacards (except Repo Cards and Raster data) have 'get' buttons. When the button is clicked, the plugin looks to see if the user has rights to clone and either allows it or delivers a pop-up modal helping the user request cloning rights. 

We would like this to change in approach. 

Every data card (Vector, RAster, PC, Repos) should have the ability to display the get button. 

Each card should look at the repo.user_capabilitues (for layers) or just user_capabilities ( for repos) to figure out if (a) it can be cloned or (via can-clone capability) or (b) it could be cloned if you requested access (via can-request-clone). 

If can-clone capability is present, show the 'get button and allow the cloning process to happen.

If can-request-clone capability is present, show the 'get button and display the "request access to Kart beta features' modal.

If neither of those exist, it shouldn't have a GET button, because you can't clone it even if you request access.

That makes sense. @hamishcampbell might be able to add more info if needed.
