### ISSUE TITLE
Update Kart to 0.14.1

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#284]
Update Kart to 0.14.1

**Comment by nyalldawson** [comment]
See https://github.com/koordinates/kart-qgis-plugin/pull/103

**Comment by nyalldawson** [comment]
Solved by https://github.com/koordinates/kart-qgis-plugin/pull/103, but will need a new release of the kart plugin (that can happen at anytime, it doesn't need to wait till the next koordinates plugin is ready)
