### ISSUE TITLE
Update Explore-sections (Popular & Recent) 

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#291]
At present Popular and recent tabs are hardcoded into the plugin. 

Please change tab presence and content as described below:

API clients need to treat the `explore-sections ` dynamically

1. Go to `explore-sections` endpoint, get list of possible sections
2. Visit each of those sections and render their contents (1, 2, then 3, 4)
 
<img width="604" alt="image" src="https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/99f1e823-2241-4349-957d-7b9fcf01941b">

1 and 2 are on this endpoint
[koordinates.com/services/api/v1.x/explore-sections/](http://koordinates.com/services/api/v1.x/explore-sections/)
3 and 4 are on corresponding section endpoints
https://koordinates.com/services/api/v1.x/explore-sections/recent/
https://koordinates.com/services/api/v1.x/explore-sections/popular/

ATM we only have popular and recent sections, but we have designed it this way so we can add new sections in future (or remove them).

**Comment by nyalldawson** [comment]
@BallJonathan 
I'm a little confused. Are we moving tabs around to match the order of the explore-sections results? Or will it always still be "popular -> browse > publishers > recent", and just dynamically hiding popular or recent if these sections aren't present in explore-sections?

**Comment by BallJonathan** [comment]
@nyalldawson This >> just dynamically hiding popular or recent if these sections aren't present in explore-sections

**Comment by benpearman** [comment]
Yes we are dynamically hiding sections if they aren't present

Note that in future, we may add more sections (atm we just have two). A
full list of these sections is available on the /explore-sections/ endpoint.

The idea is we can add or remove a section from this endpoint, and then it
will / won't render in the plugin

Order should be

Popular
Browse
Publishers
Recent
(Any other sections)

That sound right, Jonathan?

**Comment by BallJonathan** [comment]
Yep. Thanks for the better explanation!!  Much appreciated.

**Comment by BallJonathan** [comment]
@nyalldawson Just checking you saw the msgs above.

**Comment by nyalldawson** [comment]
Yep, working on it! (This isn't actually a trivial change, there's a bit involved here)

**Comment by BallJonathan** [comment]
@nyalldawson 
@benpearman asked this question awhile ago in slack. Posting here so you see it. 

" @nyalldawson had a look at the QGIS code for how its calling the explore API and saw [this](https://github.com/koordinates/koordinates-qgis-plugin/blob/51e66a23b199670d12e0f8d49e175ab70547be18/koordinates/gui/results_panel/results_panel.py#L191). Haven't tested but looks like we are only keeping panels if they contain at least one raster or vector. Any reason for this? There is also layer.rat and layer.grid layer types
[results_panel.py](https://github.com/koordinates/koordinates-qgis-plugin/blob/51e66a23b199670d12e0f8d49e175ab70547be18/koordinates/gui/results_panel/results_panel.py)
