### ISSUE TITLE
Long layer name causing text overlap. 

### ISSUE THREAD

**Issue by BallJonathan** [koordinates/koordinates-qgis-plugin#295]
Layers with long titles are causing text overlay issues. 

This can be seen in explore popular and browse

<img width="439" alt="image" src="https://github.com/koordinates/koordinates-qgis-plugin/assets/113562913/cfbab229-74f2-4cec-beb1-2fc4661ac2bd">

**Comment by nyalldawson** [comment]
@BallJonathan what should we do here? Truncate the layer names?

**Comment by BallJonathan** [comment]
Names to be truncated with "..."
