### ISSUE TITLE
DLL error generated when "Get" process followed from Koordinates plugin

### ISSUE THREAD

**Issue by gwh01** [koordinates/koordinates-qgis-plugin#299]
**Describe the bug**
When using the Koordinates plugin in QGIS to download "NZ Addresses" (for example), an error is generated when OK is clicked. screenshot attached. Error usually appears immediately.
**To Reproduce**
1. Go to 'Get'
2. Click on 'Clone to'
3. Fill out directory
4. Storage type left as "Geopackage"
5. Spatial filter = any
6. click "OK"
7. See error

**Expected behavior**
expect download of data to begin

**Screenshots**
![image](https://github.com/koordinates/koordinates-qgis-plugin/assets/105959879/7f2767e5-a410-47d8-8017-ecfbabd3a191)

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS): Windows 10 10.0.19045
 - QGIS, Kart & Plugin details: QGIS: 3.32.3-Lima, Kart plugin version 1.0.13
  ```
Paste the contents from "Plugins...Kart...About Kart" into here
Kart Plugin version
1.0.13
QGIS version
3.32.3-Lima
Operating system
Windows 10 10.0.19045
Kart version
Kart v0.14.0, Copyright (c) Kart Contributors
Â» GDAL v3.6.3; PROJ v9.2.0; PDAL v2.5.3
Â» PyGit2 v1.12.1; Libgit2 v1.6.4; Git v2.34.0.windows.1.13.g93318cbc8d; Git LFS v3.3.0
Â» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.40.1; SpatiaLite v5.0.1; Libpq v15.0.3


**Additional context**
Add any other context about the problem here.
![2023-10-31 19_12_48-Window](https://github.com/koordinates/koordinates-qgis-plugin/assets/105959879/ad5b0e14-0b80-49e4-8142-328dc8461abd)

**Comment by gwh01** [comment]
operator error

**Comment by BallJonathan** [comment]
Thanks for taking the time to report anyway. Let us know if you have any feedback.
